language: python
matrix:
  include:
    - python: "3.9-dev"
      dist: focal
    - python: "3.8"
      dist: focal
    - python: "3.7"
      dist: focal
    - python: "3.6"
      dist: focal
    - python: "3.5"
      dist: xenial
    - python: "3.4"
      dist: xenial
    - python: "2.7"
      dist: xenial
    - python: "pypy"
      dist: xenial
    - python: "pypy3"
      dist: focal
branches:
  only:
    - develop
install:
  - "pip install --upgrade pytest"
  - "pip install pytest-cov"
  - "pip install ."
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then pip install check-manifest flake8 Sphinx; fi"
script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then check-manifest; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then flake8; fi"
  - "pushd doc"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then make html; fi"
  - "popd"
  - cd test
  - "pytest --cov-report=xml --cov=latexcodec ."
after_success:
  - bash <(curl -s https://codecov.io/bash)
